# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_strategy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_strategyForm(object):
    def setupUi(self, strategyForm):
        strategyForm.setObjectName("strategyForm")
        strategyForm.resize(577, 53)
        strategyForm.setMinimumSize(QtCore.QSize(1, 1))
        strategyForm.setStyleSheet("QPushButton{\n"
"    color: rgb(126,128,125);\n"
"    border: 2px solid rgb(104, 104, 104);   \n"
"    background-color:rgb(25,29,36);\n"
"    ridge:ridge;\n"
"    padding: 4px;\n"
"    font: 75 14pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(181,151,88);\n"
"    border: 2px solid rgb(181,151,88);   \n"
"}\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(strategyForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_zqgd = QtWidgets.QPushButton(strategyForm)
        self.bt_zqgd.setObjectName("bt_zqgd")
        self.horizontalLayout.addWidget(self.bt_zqgd)
        self.bt_spjz = QtWidgets.QPushButton(strategyForm)
        self.bt_spjz.setObjectName("bt_spjz")
        self.horizontalLayout.addWidget(self.bt_spjz)
        self.bt_zbfx = QtWidgets.QPushButton(strategyForm)
        self.bt_zbfx.setObjectName("bt_zbfx")
        self.horizontalLayout.addWidget(self.bt_zbfx)
        self.bt_zrzw = QtWidgets.QPushButton(strategyForm)
        self.bt_zrzw.setObjectName("bt_zrzw")
        self.horizontalLayout.addWidget(self.bt_zrzw)
        self.bt_qrzd = QtWidgets.QPushButton(strategyForm)
        self.bt_qrzd.setObjectName("bt_qrzd")
        self.horizontalLayout.addWidget(self.bt_qrzd)

        self.retranslateUi(strategyForm)
        QtCore.QMetaObject.connectSlotsByName(strategyForm)

    def retranslateUi(self, strategyForm):
        _translate = QtCore.QCoreApplication.translate
        strategyForm.setWindowTitle(_translate("strategyForm", "Form"))
        self.bt_zqgd.setText(_translate("strategyForm", "早期过渡"))
        self.bt_spjz.setText(_translate("strategyForm", "搜牌节奏"))
        self.bt_zbfx.setText(_translate("strategyForm", "装备分析"))
        self.bt_zrzw.setText(_translate("strategyForm", "阵容站位"))
        self.bt_qrzd.setText(_translate("strategyForm", "确认展示"))
